### ISSUE TITLE
Blazor and Balero

### ISSUE THREAD

**Issue by ShalokShalom** [guettli/frow--fragments-over-the-wire#6]
I got told, and read several articles, that the C# framework Blazor, that compiles to WebAssembly, ia also Hotw, respectively Frow. (I still dont get the difference)

F# is another language on the dotnet runtime and its counterpart, that builds on top of Blazor, is called Balero.

**Comment by guettli** [comment]
thank you for this hint. 

I read this page: https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-6.0

It looks like they don't publish the wire-format. This means I don't know if this fits into fragments-over-the-wire.

do you know a page which explains the wire format?

**Comment by ShalokShalom** [comment]
I got an answer from the community

> If it's running as a webassembly, no, it's generetaed by the wasm code running in the browser. If it's a server-side Bolero (Blazor) - I am currently writing one - then yes, the HTML is rendered on server and transmitted as compressed changes over the wire to the browser"

**Comment by guettli** [comment]
@ShalokShalom sounds super interesting. But I think it does not belong into the bucket "html-fragements-over-the-wire". Good luck. Feel free to open a new issue or reopen this one.

**Comment by ShalokShalom** [comment]
How is it different?
