### ISSUE TITLE
Update on Hotwire

### ISSUE THREAD

**Issue by ShalokShalom** [guettli/frow--fragments-over-the-wire#7]
Hotwire is now, since Rails 7, the default frontend kit for Ruby on Rails and they have a new tutorial. 

https://www.hotrails.dev/

**Comment by guettli** [comment]
thank you for this hint.

I think the more general thing is hotwire, while hotrails is a particular implementation. I stick to hotwired for the next weeks.

feel free to ask again or create a PR if you want something to get improved.

**Comment by ShalokShalom** [comment]
Hotrails is just the name of the tutorial
